### ISSUE TITLE
AS4 RFC 2392 issue

### ISSUE THREAD

**Issue by clancger** [difi/Oxalis-AS4#10] opened 2019-02-08 15:03 UTC
Pls see below the comments from IBM Architect.
We confirm the prior RFC 2822 error seems resolved however.

Near as I can figure, the content ID (cid specifications in the SOAP Envelope Header are incorrect (there are 3 of them).  They do not conform to RFC2392, which requires that they are URL encoded. 

So for example, the following reference from the document that was sent to us:
<eb:PartInfo href="cid:07e22830-c58e-4949-902c-cef44fac7acd@17c9b254946f">

Should be formatted like this (note that the @ at sign has been replaced with %40):<eb:PartInfo href="cid:07e22830-c58e-4949-902c-cef44fac7acd%4017c9b254946f">

The normative reference for this is the Web Services Security SOAP Message with Attachments (SwA) Profile Version 1.1.1, It says that the <xenc:CipherReference> URL MUST be a URL that refers to the MIME part containing the cipher text, and must also correspond to the reference value of the original attachment that was encrypted.

This MUST be a CID scheme URL [as specified in RFC2392].RFC2392 Content-ID and Message-ID Uniform Resource Locators says that "Since addr-spec in a Message-ID or Content-ID might contain characters not allowed within a URL; any such character must be hex-encoded using the %hh escape mechanism in [URL] 

![as4 rfc2392 issue](https://user-images.githubusercontent.com/1429765/52486307-a4566380-2b6f-11e9-8c0c-4822fe15dfb3.jpg)

**Comment by jerouris** [comment] 2019-02-14 20:05
Hi Ger,
I think that you might be wrong here. When it comes to URL (and RFC 2822), the @ character is a special character that is used as a separator between the UUID and the domain, and for this reason this @ should not be URL encoded. If there is a "@" inside the UUID or the domain then that "@" should be URL encoded, but not the one that is used as a separator. 

This also holds for example for message ID  the "/" character is special and used for splitting a message Id from a contend id. this "/" character must not be encoded.

Please have a look also at the examples found in RFC 2392, where you will see that the "@" separating the domain from the name/uuid is not URL encoded

**Comment by clancger** [comment] 2019-02-15 15:54
Hi Jerry,

Here is the response from my team.. I hope this clarifies 

They are confused.  We are talking about completely different fields.  RFC2822 applies to the message ID,  URL encoding applies to the content ID.

The message ID should not be URL encoded.

So they are correct about that.  The problem is that they don’t understand that we aren’t talking about the message ID anymore.  That is fixed.

The content ID is a reference that points to later down into the message.  It identifies where the payload begins in the message.  Because we are expecting the reference to be URL encoded, we can’t find the payload.

**Comment by jerouris** [comment] 2019-02-15 16:13
OK, to avoid confusion then, I'm doing the following statement:

The xml element `<eb:PartInfo href="cid:07e22830-c58e-4949-902c-cef44fac7acd@17c9b254946f">` is correct according to the RFCs because the @ is a special character that is used to split the uuid from the domain and for that it shouldn't not be URL Encoded. It points to a part with the following headers:
```
--boundary-example-1

     Content-ID: <07e22830-c58e-4949-902c-cef44fac7acd@17c9b254946f>
     Content-Type: application/pdf
     Content-Transfer-Encoding: BASE64

     R0lGODlhGAGgAPEAAP/////ZRaCgoAAAACH+PUNvcHlyaWdodCAoQykgMTk5
     NSBJRVRGLiBVbmF1dGhvcml6ZWQgZHVwbGljYXRpb24gcHJvaGliaXRlZC4A
     etc... 
```
This is what is also stated in RFC 2392 (see examples in RFC page 3 and page 4)
Please agree or correct the above statement accordingly taking into account the examples in RFC.

**Comment by clancger** [comment] 2019-02-15 21:08
Apologies for the delays in responses, I'm in California this week.
Pls see below the feedback 

"Disagree.  There is no domain name in a content ID.
The domain name is part of the message ID>
I think they are confusing RFC 2822 and RFC 2392"

**Comment by jerouris** [comment] 2019-02-15 21:58
Just to be as specific as possible:
RFC 2392 states (Section 2):
```
content-id      = url-addr-spec
url-addr-spec = addr-spec  ; URL encoding of RFC 822 addr-spec
```
and RFC 822 states (Section 6.1)
addr-spec   =  local-part "@" domain        ; global address
```
Also see the example in RFC 2392, in which the '@' sign is not URL encoded. 
Copied also here for brevity:
```
   --boundary-example 1
     Content-Type: Text/HTML; charset=US-ASCII

     to the other body part, for example through a statement such as:
     <IMG SRC="cid:foo4*foo1@bar.net" ALT="IETF logo">

     --boundary-example-1

     Content-ID: <foo4*foo1@bar.net>
     Content-Type: IMAGE/GIF
     Content-Transfer-Encoding: BASE64

     R0lGODlhGAGgAPEAAP/////ZRaCgoAAAACH+PUNvcHlyaWdodCAoQykgMTk5
     NSBJRVRGLiBVbmF1dGhvcml6ZWQgZHVwbGljYXRpb24gcHJvaGliaXRlZC4A
     etc...

     --boundary-example-1--
```

**Comment by clancger** [comment] 2019-02-15 22:48
inviting @dhixon

**Comment by dhixon** [comment] 2019-02-19 16:14
OK.  My apologies.  I believe that Jerry is correct.  RFC 2392 defines mid: and cid: the same and the @ is valid.  Now I believe the problem is that the MIME Content-ID of the message we were sent is missing the angle brackets ("<" and ">").  The Content-ID as sent:

Content-ID: fa88b997-6844-4d1f-9f75-4ad3e6105060@17c9b254946f

The Content-ID as it should be:

Content-ID: <fa88b997-6844-4d1f-9f75-4ad3e6105060@17c9b254946f>

This is mentioned in the same RFC (2392) "Corrected the example messages to have the correct Content-ID form; they now use the angle brackets." and also "Notes: In Internet mail messages, the addr-spec in a Content-ID [MIME] or Message-ID [822] header is enclosed in angle brackets"

**Comment by JesperLarsenOO** [comment] 2019-02-22 14:19
I was able to verify this by looking at some AS4 message dumps sent from Oxalis AS4 
The angle brackets on Content-ID is missing and according to RFC (2392) the Content-ID must have angle brackets 
@DIFI: Can you let us know what you think of this? 
Thank you

**Comment by evenos** [comment] 2019-03-04 12:26
Hi all.

We agree that the Content-ID MIME header value must be wrapped in angled brackets ```<...>```.
We have added a preliminary implementation in our CEF conformance test branch ([conformance-ongoing](https://github.com/difi/Oxalis-AS4/commit/2d950ddda09255306e4b64d8b38160fc19823157)).

We are currently in a process of evaluating the test results of the conformance tests and planning some fixes where there still is some deviations.

Would you let us know if you can run your test out of this branch, of if a new RC release would be necessary?

**Comment by artjomsk** [comment] 2019-03-04 13:45
> Would you let us know if you can run your test out of this branch, of if a new RC release would be necessary?

@JesperLarsenOO what do you think? We can put changes from the branch to our test AccessPoint and send something through AS4

**Comment by JesperLarsenOO** [comment] 2019-03-04 14:00
This is sort of two way. 
We need this fix applied to the Oxalis instance used for PEPPOL Onboarding and test so that this Oxalis instance sends the AS4 message instances with angle brackets. I suppose only DIFI can do that update to that instance.
And then yes is artjomsk can do a full test on the testbed just taking the changes from the branch fine for me. 
I suppose a final version will be made contatining all the fixes from you CEF conformance test aswell later on? That will then be the required version for Oxalis AS4 user in PEPPOL.

**Comment by clancger** [comment] 2019-03-04 18:16
Hi all,

For sure the IBM preference would be getting the testbed version patched
and working properly as opposed to trying to bend our deployment to fit.

**Comment by clancger** [comment] 2019-03-04 21:11
Is there any estimate of when the the testbed could be patched?

**Comment by evenos** [comment] 2019-03-13 10:33
We have just released an new [RC](https://github.com/difi/Oxalis-AS4/releases/tag/4.1.0-RC5) containing a fix for this issue.

**Comment by JesperLarsenOO** [comment] 2019-03-13 10:53
Hi Evenos,

Could you make someone apply this patch to the the DIFI Oxalis test? - that is the one we use for the PEPPOL testbed

This one: https://test-vefa.difi.no/tbap/as4

Thank you

**Comment by abhiroopgupta** [comment] 2019-03-18 16:34
Hi,
I have been trying to deploy RC5 and get the openPeppol tests done.
But I cannot get the Oxalis Standalone working with RC5 of AS4 plugin.

Firstly, I replaced all the distribution JAR's in the as4 directory and tried to run the command to send files. 
It gave an error :: **_"Unable to initiate 'class no.difi.vefa.peppol.lookup.locator.BdxlLocator'"_**
From the stacktrace: 
**_Caused by: com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'lookup.locator.hostname'
        at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)_**

I tried to add **_'lookup.locator.hostname'_** to the configuration to get through this problem. I tried both "test-smp.peppol.gr" & "test-smp.difi.no".

When I set **_lookup.locator.hostname=test-smp.peppol.gr_** and try to send a profile to recipient with id **_0088:tbcntrl00002_**
i get an error "**_Identifier 'iso6523-actorid-upis::0088:tbcntrl00002' is not registered in SML._**"  

The actorid is indeed registered in the SMP with the profile i tried to send and can be verified here http://test-smp.peppol.gr/iso6523-actorid-upis%3A%3A0088%3Atbcntrl00002/

I do not know what has gone wrong with the RC5 but sending the same file with AS4 RC4 plugin doesn't require the configuration **_'lookup.locator.hostname'_**.

Is this required now? and if so what value should be used?

/Abhiroop

**Comment by abhiroopgupta** [comment] 2019-04-01 11:28
Any update here?

**Comment by jannewaren** [comment] 2019-04-08 10:48
Hello @abhiroopgupta 

To me it looks like this configuration parameter is now required since RC4 or RC5. Too bad it has not been mentioned in any release notes 😢 

I have managed to get it working in testing environment by specifying like this:

`lookup.locator.hostname="acc.edelivery.tech.ec.europa.eu"`

In production it will probably have to look like this:

`lookup.locator.hostname="edelivery.tech.ec.europa.eu"`

**Comment by mindweaver** [comment] 2019-04-25 08:27
I am also getting this error. Where did you put the lookup.locator-string? I tried oxalis.conf but it is not working. Same error message.

**Comment by ekorra** [comment] 2019-05-14 13:15
@jannewaren 
locator.hostname should be set automaticly by Oxalis based on the OpenPEPPOL certificate CA (Test/Prod)
If this is not working for you, you shold open an issue at the [Oxalis repo](https://github.com/difi/oxalis)

**Closed by ekorra** 2019-05-14 13:15 UTC

**Comment by senikk** [comment] 2019-09-17 11:48
This is still an issue with Oxalis AS4 RC8. I can't get it work anymore without setting lookup.locator.hostname in my reference.conf file

![image](https://user-images.githubusercontent.com/400752/65038960-703af080-d951-11e9-9584-8e529a5895ce.png)

Since Oxalis AS4 RC8 also gives mode "test" instead of production could this be related? /ref #24
