### ISSUE TITLE
Not registered in SML

### ISSUE THREAD

**Issue by senikk** [difi/Oxalis-AS4#99] opened 2020-02-27 07:55 UTC
Everyday approx 100 attempts to send fails with "Identifier 'iso6523-actorid-upis::0192:xxxxxxxxx' is not registered in SML.". Lists of such failed attempts is also sent to elma@digdir.no Everytime checking manually afterwards its registered in SML and its possible to send again successfully. We also check before we send it to Oxalis to check what type of document to generate so we shouldn't have so many of these errors.

Some receiver peppol addresses have the same error several times in one day, most of them twice, but 89% of the failed attempts just happens once. This was from 26.2.2020. Looking at the one with 5 errors, 48 invoices is sent successfully to the same receiver the same day, successfully both before and after the ones with this error.

These lookup errors also happens to receivers registered with our own accesspoint.

Here is one of the loggings for these kind of errors:

`no.difi.oxalis.api.lang.OxalisTransmissionException: Identifier 'iso6523-actorid-upis::0192:989996355' is not registered in SML.
              at no.difi.oxalis.outbound.lookup.CachedLookupService.lookup(CachedLookupService.java:73)
              at no.difi.oxalis.api.lookup.LookupService.lookup(LookupService.java:57)
              at no.difi.oxalis.outbound.transmission.TransmissionRequestBuilder.build(TransmissionRequestBuilder.java:208)
              at no.unimicro.ap.outbox.UniSendService.sendFileToReceiver(UniSendService.java:173)
              at no.unimicro.ap.outbox.UniSendService.main(UniSendService.java:111)
Caused by: no.difi.vefa.peppol.lookup.api.LookupException: Identifier 'iso6523-actorid-upis::0192:989996355' is not registered in SML.
              at no.difi.vefa.peppol.lookup.locator.BdxlLocator.lookup(BdxlLocator.java:105)
              at no.difi.vefa.peppol.lookup.LookupClient.getServiceMetadata(LookupClient.java:80)
              at no.difi.vefa.peppol.lookup.LookupClient.getEndpoint(LookupClient.java:114)
              at no.difi.oxalis.outbound.lookup.CachedLookupService.load(CachedLookupService.java:79)
              at no.difi.oxalis.outbound.lookup.CachedLookupService.load(CachedLookupService.java:46)
              at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628)
              at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2336)
              at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295)
              at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208)
              at com.google.common.cache.LocalCache.get(LocalCache.java:4053)
              at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4057)
              at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4986)
              at no.difi.oxalis.outbound.lookup.CachedLookupService.lookup(CachedLookupService.java:71)
              ... 4 more
`

**Comment by senikk** [comment] 2020-03-03 12:22
Still lots of these every day, any news? Anyone know something about what could be the reason for this issue?

**Comment by klakegg** [comment] 2020-03-04 11:12
This is a question related to ELMA. Please report to elma@digdir.no for such resports.

**Comment by johannmo** [comment] 2020-03-06 12:17
@senikk Reading your initial description of this issue, I get the following - please correct me if I am wrong:

1. You attempt to send, but get the error message "Identifier 'iso6523-actorid-upis::0192:xxxxxxxxx' is not registered in SML.".
2. You check whether the subject participant is registered in SML, and find that it is registered.
3. You try sending again, and the attempt is successful.

Are these assumptions correct?

**Comment by senikk** [comment] 2020-03-09 08:13
Yes. Its also checked before sending in our own code before sending trought Oxalis because we decide which format to convert to so this shouldn't almost never happen. On friday there was none such errors until 11:02. Still no such errors today so I have to watch what is happening later on.

**Comment by johannmo** [comment] 2020-03-09 08:50
> @senikk Reading your initial description of this issue, I get the following - please correct me if I am wrong:
> 
> 1. You attempt to send, but get the error message "Identifier 'iso6523-actorid-upis::0192:xxxxxxxxx' is not registered in SML.".
> 2. You check whether the subject participant is registered in SML, and find that it is registered.
> 3. You try sending again, and the attempt is successful.
> 
> Are these assumptions correct?

So if we leave out the possibility that someone has manually added the participant above to SML in the (presumably short) timeframe between points 1 and 2 above, our SMP has taken care of its responsibility of updating the SML.

IMHO the root cause is either in the SML service itself, or in the libraries used for querying this service.

**Comment by senikk** [comment] 2020-03-11 08:49
One step closer to resolve this now. I found a few DNS host lookup type of errors in our Oxalis logs which got me to take a deeper look at the coredns logs in our Kubernetes cluster. And in these logs I found several read udp i/o timeout errors against xxx.iso6523-actorid-upis.edelivery.tech.ec.europa.eu type of addresses.

**Comment by senikk** [comment] 2020-03-17 14:30
"CEF discovered some discrepancies between two DNS server nodes that led to “non-ideal” propagation of DNS entries."

This could be the main reason for lots of problems lately with iso6523-actorid-upis.edelivery.tech.ec.europa.eu addresses. Still no such errors today.

**Comment by FrodeBjerkholt** [comment] 2020-03-18 07:43
We got the following message from CEF today:

Hello,

There was an issue with one of the DNSSEC signing key, which was expired.
Today it was renewed and this supposed to fix the lookup failures.
However it is vital to clear all DNS cache locally and if possible also on the resolver DNS.
While the network team investigating your issue, could you please ensure this flushing/cleaning and check again whether it solves your issue. 


Kind regards,

Denes Varszegi,

CEF EDELIVERY SUPPORT

**Comment by johannmo** [comment] 2020-03-18 09:53
Closing this in a couple of days UNO.

**Closed** 2020-03-20 09:00 UTC
Labels: question
